global:
  datacenter: dc-3
  name: consul
  domain: consul
  image: 'hashicorp/consul-enterprise:1.10.1-ent'
  tls:
    enabled: true
    caCert:
      secretName: consul-federation
      secretKey: caCert
    caKey:
      secretName: consul-federation
      secretKey: caKey
  federation:
    enabled: true
  acls:
    manageSystemACLs: true
    replicationToken:
      secretName: consul-federation
      secretKey: replicationToken
  gossipEncryption:
    secretName: consul-federation
    secretKey: gossipEncryptionKey
  enableConsulNamespaces: true
connectInject:
  enabled: true
  default: true
  transparentProxy:
    defaultEnabled: true
  envoyExtraArgs: "--log-level debug"
  consulNamespaces:
    mirroringK8S: true
controller:
  enabled: true
meshGateway:
  enabled: true
  replicas: 3
# ingressGateways:
#   enabled: true
#   gateways:
#     - name: ingress-gateway
#       service:
#         type: LoadBalancer
server:
  extraConfig: |
    {
      "primary_datacenter": "dc-1",
      "primary_gateways": ["13.36.37.27:443"]
    }
ui:
  service:
    type: LoadBalancer
syncCatalog:
  enabled: true
  consulNamespaces:
    mirroringK8S: true
  k8sDenyNamespaces: ["kube-system", "kube-public", "consul"]